# Generated by Django 5.2.8 on 2025-11-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_checkoutlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutlist',
            name='user',
        ),
    ]
