# Generated by Django 5.2.8 on 2025-11-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_cash_received_order_change_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cash_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='change_given',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='printed_at',
        ),
    ]
