# Generated by Django 5.2.8 on 2025-11-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_cash_received_order_change_given_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
